apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 2
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      name: web-app
      labels:
        app: kubia
    spec:
      containers:
        - name: udacity-capstone
          image: AbdulazizGH/udacity-capstone
          imagePullPolicy: Always
  selector:
    matchLabels:
      app: web-app
